[project]
name = "aws-novamart-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dhnhut@gmail.com", email = "dhnhut@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.93",
    "python-dotenv>=1.2.3",
]

[project.scripts]
aws-novamart-agents = "aws_novamart_agents:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
